from .s3_image_node import NODE_CLASS_MAPPINGS as S3_IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as S3_IMAGE_NAMES
from .s3_video_node import NODE_CLASS_MAPPINGS as S3_VIDEO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as S3_VIDEO_NAMES
from .azure_image_node import NODE_CLASS_MAPPINGS as AZ_IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AZ_IMAGE_NAMES
from .azure_video_node import NODE_CLASS_MAPPINGS as AZ_VIDEO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AZ_VIDEO_NAMES
from .latent_save_output_node import NODE_CLASS_MAPPINGS as LATENT_SAVE_OUTPUT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LATENT_SAVE_OUTPUT_NAMES
from .conditioning_load_json_node import NODE_CLASS_MAPPINGS as CONDITIONING_LOAD_JSON_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONDITIONING_LOAD_JSON_NAMES
from .conditioning_save_json_node import NODE_CLASS_MAPPINGS as CONDITIONING_SAVE_JSON_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONDITIONING_SAVE_JSON_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

for mappings in [S3_IMAGE_MAPPINGS, S3_VIDEO_MAPPINGS, AZ_IMAGE_MAPPINGS, AZ_VIDEO_MAPPINGS, LATENT_SAVE_OUTPUT_MAPPINGS, CONDITIONING_LOAD_JSON_MAPPINGS, CONDITIONING_SAVE_JSON_MAPPINGS]:
    NODE_CLASS_MAPPINGS.update(mappings)

for names in [S3_IMAGE_NAMES, S3_VIDEO_NAMES, AZ_IMAGE_NAMES, AZ_VIDEO_NAMES, LATENT_SAVE_OUTPUT_NAMES, CONDITIONING_LOAD_JSON_NAMES, CONDITIONING_SAVE_JSON_NAMES]:
    NODE_DISPLAY_NAME_MAPPINGS.update(names)